vsync = true;
backend = "glx";
unredir-if-possible = false;
use-damage = false;
xrender-sync-fence = true;
detect-client-opacity = true;
detect-rounded-corners = true;

corner-radius = 8;
rounded-corners-exclude = [ "window_type = 'dock'" ];

shadow = true;
shadow-radius = 12;
shadow-opacity = 0.45;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-exclude = [ "window_type = 'dock'", "class_g = 'slock'" ];

fading = true;
fade-in-step = 0.06;
fade-out-step = 0.06;
fade-delta = 8;

