#!/bin/sh

clock=$(date '+%H')

case "$clock" in
	"00"|"12") icon="" ;;
	"01"|"13") icon="" ;;
	"02"|"14") icon="" ;;
	"03"|"15") icon="" ;;
	"04"|"16") icon="" ;;
	"05"|"17") icon="" ;;
	"06"|"18") icon="" ;;
	"07"|"19") icon="" ;;
	"08"|"20") icon="" ;;
	"09"|"21") icon="" ;;
	"10"|"22") icon="" ;;
	"11"|"23") icon="" ;;
esac

case $BLOCK_BUTTON in
	1) notify-send "This Month" "$(cal | sed "s/\<$(date +'%e'|tr -d ' ')\>/<b><span color='red'>&<\/span><\/b>/")" && notify-send "Appointments" "$(calcurse -d3)" ;;
	2) setsid -f "$TERMINAL" -e calcurse ;;
	3) notify-send "📅 Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Middle click opens calcurse if installed" ;;
	6) setsid -f "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

dateStr=$(date "+%a %d/%m %H:%M")
echo "| $dateStr"
